version: '3'
services:
  php:
    tty: true
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=http-helper.local"
    build:
      context: ./build/.
    volumes:
      - .:/app
      - ./build/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini