name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.0, 8.1, 8.2, 8.3, 8.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            vendor
            ~/.composer/cache
          key: composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit -c phpunit.xml --coverage-text

      - name: Run ECS checks
        run: vendor/bin/ecs check src
